### PR TITLE
fix: minify infinity in expressions

### LINKED ISSUE #839: minify-infinity not doing anything
**Describe the bug**

The minify-infinity pass doesn't do anything.

**To Reproduce**

```js
const infinities = [Infinity, 1/0, true/false, !0/!1, true/(true/(true/false))];
const zeroes = [1/Infinity, 1/(1/0), false/true, !1/!0, true/(true/false)];
const justone = Infinity;
alert(Infinity);
```

**Actual Output**

```js
"use strict";var infinities=[Infinity,1/0,!0/!1,!0/!1,!0/0],zeroes=[1/Infinity,0,0,0,0],justone=Infinity;alert(Infinity);
```

**Expected Output**

```js
"use strict";var infinities=[1/0,1/0,1/0,1/0,1/0],zeroes=[0,0,0,0,0],justone=1/0;alert(1/0);
```

**Additional context**

It returns here, and therefore doesn't do the substitution:
```js
        if (path.isLVal() && !path.parentPath.isExpressionStatement()) {
          return;
        }
```
The `path.parentPath.type` is `"ArrayExpression"`, `"BinaryExpression"`, `"VariableDeclarator"` and `"CallExpression"`, respectively.

I couldn't find any documentation on what `.isExpressionStatement()` is actually supposed to do, so I don't know whether the bug is in minify-infinity or in babel itself.

### PR DESCRIPTION
**Pull request by boopathi**
Fix #839

### CODE REVIEW

File: packages/babel-plugin-minify-infinity/__tests__/fixtures/expressions/expected.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+let x = [1 / 0, 1 / 0];
+let y = [{
+  a: Infinity
```
Comment (Cyp) [inline packages/babel-plugin-minify-infinity/__tests__/fixtures/expressions/expected.js]: Should expect `  a: 1 / 0`, I think.

File: packages/babel-plugin-minify-infinity/src/index.js [hunk 2]
```diff
@@ -27,11 +27,16 @@ module.exports = function({ types: t }) {
         if (path.parentPath.isMemberExpression()) {
           return;
         }
-
         const bindingIds = path.parentPath.getBindingIdentifierPaths();
```
Comment (Cyp) [inline packages/babel-plugin-minify-infinity/src/index.js]: Seems to work. If I'm reading it right, could
```js
        for (const id of Object.keys(bindingIds)) {
          if (
            id === "Infinity" &&
            bindingIds[id] === path &&
            // ObjectProperty is common for ObjectExpression and ObjectPattern and only
            // one of them is a Binding, the other is simply a reference
            !path.parentPath.parentPath.isObjectExpression()
          ) {
            return;
          }
        }
```
be simplified to this?
```js
        if (
          bindingIds["Infinity"] === path &&
            // ObjectProperty is common for ObjectExpression and ObjectPattern and only
            // one of them is a Binding, the other is simply a reference
            !path.parentPath.parentPath.isObjectExpression()
          ) {
          return;
        }
```
