### PR TITLE
fix(mangle) - mark the correct eval scope during mangling

### LINKED ISSUE #366: babili is removing function arguments in scope of eval call
The following code:

```js
'use strict';
function myEval(code, _var_) {
  eval(code);
}
myEval('console.log(_var_)', 'myValue');
```

Is transformed to:
```js
'use strict';function myEval(code){eval(code)}myEval('console.log(_var_)','myValue');
```

Which does not work.

I'm using `babel-preset-babili` v0.0.9. The bug was not present in v0.0.5. I suppose it was introduced in https://github.com/babel/babili/commit/10b114f26533a58f66bb8a8ae90335c7353d1085.

### LINKED ISSUE #605: Deadcode erroneously mangling names wrt eval?
When using the 'cheap-module-eval-source-map' devtool mode, Webpack 3.x (also 2.x) generates code like

```javascript
webpackJsonp([0],[
/* 0 */,
/* 1 */,
/* 2 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
eval("\n\nvar global = __webpack_require__(13),\n    core = __webpack_require__(113),\n    hide = __webpack_require__(33),\n    redefine = __webpack_require__(53),\n ...");
```

When using Webpack's Babili plugin (`new BabiliPlugin()`, i.e. passing the code through to `babel-preset-babili@0.1.4`), this gets mangled to

```javascript
webpackJsonp([0],[,,function(c,e,t){"use strict";eval("\n\nvar global = __webpack_require__(13),\n    core = __webpack_require__(113),\n    hide = __webpack_require__(33),\n    redefine = __webpack_require__(53), ...");
``` 

which naturally doesn't work due to the parameters used by the `eval` code being renamed. :crying_cat_face:

Curiously enough, though, setting `{deadcode: false}` (_not_ `mangle`, as one might expect), fixes this! With `new BabiliPlugin({deadcode: false})`, the generated code looks like

```javascript
webpackJsonp([0],[,,function(module,exports,__webpack_require__){"use strict";eval("\n\nvar global = __webpack_require__(13),\n    core = __webpack_require__(113),\n    hide = __webpack_require__(33),\n    redefine = __webpack_require__(53), ...");
```

which does work.

I know it's something of an edge case to have devtools enabled in babilified builds (and in fact it was a mistake on my side to begin with), but this still smells like a bug.

For those searching for this issue and how to solve it, the exception is:
> Uncaught ReferenceError: `__webpack_require__` is not defined at eval

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
We were always checking the wrong scope that was marked by DCE in another pass. 

+ fixes #366 
+ fixes #605

### CODE REVIEW

File: packages/babel-plugin-minify-mangle-names/src/index.js [hunk 1]
```diff
@@ -480,7 +481,9 @@ module.exports = babel => {
           } else {
             throw new Error(
               `Unexpected Rename Error: ` +
-                `Trying to replace "${node.name}": from "${oldName}" to "${newName}". ` +
+                `Trying to replace "${
```
Comment (vigneshshanmugam) [inline packages/babel-plugin-minify-mangle-names/src/index.js]: prettier formatting.

File: packages/babel-plugin-minify-mangle-names/src/index.js [hunk 2]
```diff
@@ -480,7 +481,9 @@ module.exports = babel => {
...
+                  node.name
```
Comment (boopathi) [inline packages/babel-plugin-minify-mangle-names/src/index.js]: maybe update prettier that's used in your editor? Also, is `yarn fix` changing this too ?

Comment (vigneshshanmugam) [reply packages/babel-plugin-minify-mangle-names/src/index.js]: yarn fix doesnt change this but changes some other things.. I have updated the editor prettier.. something weird.

**Comment by vigneshshanmugam** [comment]
@boopathi restart appveyor build, some caching issue and add me there.

**Comment by boopathi** [comment]
> add me there

I can't find where to add. I'll check it.

**Comment by vigneshshanmugam** [comment]
Omg appveyor, crazy slow. 7 mins and counting.
