### PR TITLE
Do not inline RegExp literals in loop assignment

### LINKED ISSUE #981: minify-dead-code-elimination cause regexp match infinite loop.
**Describe the bug**

**To Reproduce**

Minimal code to reproduce the bug

```js
function getElementTransforms(el) {
  if (!is.dom(el)) return;
  const str = el.style.transform || '';
  const reg = /(\w+)\(([^)]*)\)/g;
  const transforms = new Map();
  let m; while (m = reg.exec(str)) transforms.set(m[1], m[2]);
  return transforms;
}
```

**Actual Output**

If there is no Error thrown,

```js
function getElementTransforms(el) {
  if (!is.dom(el)) return;
  var str = el.style.transform || '';
  var transforms = new Map();
  var m;

  while (m = /(\w+)\(([^)]*)\)/g.exec(str)) {
    transforms.set(m[1], m[2]);
  }

  return transforms;
}
```

**Expected Output**

```js
function getElementTransforms(el) {
  if (!is.dom(el)) return;
  var str = el.style.transform || '';
  var reg = /(\w+)\(([^)]*)\)/g;
  var transforms = new Map();
  var m;

  while (m = reg.exec(str)) {
    transforms.set(m[1], m[2]);
  }

  return transforms;
}
```

**Configuration**
Can be reproduce Using [Babel's Online Try Out](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAcwKZQKIBtUFtVhQAqATgIZgDOwcJulAFKlgJSIDeAUIojMIgwCEMSgDoAJnFxNWbEuhAkwAbm6IICSlERaSiALyJmorQE8coqOSo06iAD73EAcmeqeGqtvnIDiAPQMADoA7gDULEEMDADaAHosALoAVJEs_sju6praVhTUtPR-YKghiACyZAAODCxZONq4yoghABYwOAK4fj6iqAAeqBAMuixseTaFYpToDLgxAIyJADSI8wBMiXVq8lCKSBMFdJSqAL5AA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-3&prettier=false&targets=&version=7.9.0&externalPlugins=babel-plugin-minify-dead-code-elimination%400.5.1)

`babel-minify CLI`

babel-plugin-minify-dead-code-elimination: `0.5.1`

babel version : `7.9.0`

babel-minify-config: default without config

### PR DESCRIPTION
**Pull request by JLHwung**
This PR also bumps `@babel/*` to 7.9.0 so we are testing against latest Babel 7

Fixes #981

### CODE REVIEW

**Comment by wssgcg1213** [comment]
CI failed @JLHwung

File: packages/babel-plugin-transform-merge-sibling-variables/__tests__/fixtures/lift-different-declars/actual.js [hunk 1]
```diff
@@ -1,3 +1,3 @@
 for (let i = 0; i < 0; i++) {
-  var i = 0;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-merge-sibling-variables/__tests__/fixtures/lift-different-declars/actual.js]: It is a syntax error since `i` has been declared. I have revised to declare `i` in block statement.

**Comment by hexydec** [comment]
Any chance of this getting merged?

**Comment by zoolsher** [comment]
Will this PR get merged? 😢
