### PR TITLE
fix: account for different scopes during path evaluation

### LINKED ISSUE #574: if statement wrongly removed when var declaration inside conditional block
It seems that when you declare and initialize a variable in a code block that executes conditionally, it is assumed that the variable will have this value also outside of the code block. This is wrong when the conditional code block does not get executed, in which case the variable will be undefined. As a result, further optimizations, like removing if statements, produce wrong results.

E.g., the following code produces a wrong result

```js
function x(v) {
  if (v) var w = true;
  if (w) console.log("hello",v);
}

x(false);
x(true);
```

It produces this:

```js
function x(a){if(a);console.log("hello",a)}x(!1),x(!0);
```

Which, when executed, outputs:

```
hello false
hello true
```

while it should only output the second line.

A related problem is with this code:

```js
function x(v) {
  if (v) {var w = [];for (let i=0;i<1;i++) w.push("hello");}
  if (w) for (let i=0;i<w.length;i++) console.log(w[i],v);
}

x(false);
x(true);
```

Which produces:

```js
function x(a){if(a){var b=[];for(let a=0;1>a;a++)b.push("hello")}for(let c=0;c<b.length;c++)console.log(b[c],a)}x(!1),x(!0);
```

When executed this throws an exception `Cannot read property 'length' of undefined`.

However, unlike the previous example, when disabling the `minify-dead-code-elimination` plugin, this produces correct code.

The latter example is what happens for example when processing the firebase scripts (see: https://github.com/Polymer/polymer-cli/issues/701)

### LINKED ISSUE #810: "if" condition is incorrectly omitted after minify
#### Input Code

```js
if (false) {
  var bar = true;
}
if (bar) {
  alert('bug!');
}
```

#### Actual Output

```js
var bar;alert('bug!');
```

#### Expected Output

```js
var bar;bar&&alert('bug!');
```

#### Details

The if condition is incorrectly removed. The logic is changed.

I know that putting var inside a block scope is definitely a bad practice. I've just tried to minify some legacy codes and encountered this critical issue.

Example: [See it here in repl](https://babeljs.io/repl#?babili=true&browsers=&build=&builtIns=false&code_lz=JYMwBAFCCGA2DOBTAlGA3gKDGAbtATmAEYFgC8YALvgK6IDcGAvhqJCfqptnIvpRADkRGgHMAhIOSMWGIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=babili&prettier=false&targets=&version=6.26.0&envVersion=)

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #810 

+ fix #574  properly

### CODE REVIEW

File: packages/babel-plugin-minify-dead-code-elimination/src/index.js [hunk 1]
```diff
@@ -976,10 +976,14 @@ module.exports = ({ types: t, traverse }) => {
     } else {
       path.traverse({
         VariableDeclaration(varPath) {
-          if (!varPath.isVariableDeclaration({ kind: "var" })) return;
+          const { node } = varPath;
+
+          if (node.kind !== "var") {
+            return;
+          }
```
Comment (boopathi) [inline packages/babel-plugin-minify-dead-code-elimination/src/index.js]: why is this changed? Let's stick to `.isType( params )`

Comment (boopathi) [reply packages/babel-plugin-minify-dead-code-elimination/src/index.js]: isVariableDeclaration has `kind` ... So let's change it back.

File: packages/babel-helper-evaluate-path/src/index.js [hunk 2]
```diff
@@ -113,8 +113,12 @@ function evaluateBasedOnControlFlow(binding, refPath) {
       return { shouldDeopt: true };
     }
 
-    let blockParent = binding.path.scope.getBlockParent().path;
     const fnParent = binding.path.getFunctionParent();
+    if (!fnParent) {
+      return { shouldDeopt: true };
+    }
+
+    let blockParent = binding.path.scope.getBlockParent().path;
```
[the remark this answers is not in the document]
Comment (vigneshshanmugam) [reply packages/babel-helper-evaluate-path/src/index.js]: Block parent cannot be null, it returns Program path.
