### PR TITLE
Fix folding array literals - bail on spread element

### LINKED ISSUE #628: Some of the plugin in this preset delete array reverse call
Babili deletes array reverse call (and probably something else as well)
```bash
npm install babel-preset-babili
echo '[...a].reverse()' | babel --presets=babili
```

And the result is
```js
[...a]
```
`reverse()` disappears for no reasons

### LINKED ISSUE #695: Array spread with function call broken in 0.2.0
#### Input Code

```js
function foo()
{
	return [...bar].reverse();
};
```

#### Actual Output
```js
function foo() {
	return [...bar]; // oops - where did reverse() go?
}
```

#### Expected Output

```js
function foo() {
	return [...bar].reverse();
}
```

#### Details
I'd suspect it is reversing the elements in the array literal and removing the reverse() call, but it does not take in to account spread.
Workaround:
```js
function foo()
{
	const ret = [...bar];
	return ret.reverse();
};
```
This keeps the reverse() call after minify.

### PR DESCRIPTION
**Pull request by boopathi**
+ Fixes #695
+ Fixes #628
+ Related #610

### CODE REVIEW

File: packages/babel-plugin-minify-constant-folding/src/replacements.js [hunk 1]
```diff
@@ -51,7 +58,7 @@ module.exports = ({ types: t }) => {
               return evaled.value;
             })
             .join(sep.value);
-          return bad ? undefined : t.stringLiteral(str);
+          return bad ? void 0 : t.stringLiteral(str);
```
Comment (j-f1) [inline packages/babel-plugin-minify-constant-folding/src/replacements.js]: Why does this use `void 0` instead of `undefined`?

Comment (boopathi) [reply packages/babel-plugin-minify-constant-folding/src/replacements.js]: we use `void 0` everywhere in the project. Just sticking to that.
