### PR TITLE
fix: handle non array statements in evaluate helper

### LINKED ISSUE #844: Something went wrong when updating
After updating
```
$ npm update
+ babel-preset-env@1.7.0
+ babel-preset-minify@0.4.2
```
I get
```
~/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Cannot find module '@babel/types' (While processing preset: "~/project/node_modules/babel-preset-minify/lib/index.js")
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/project/node_modules/babel-helper-evaluate-path/lib/index.js:11:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
, and downgrading again doesn't help.

Not sure if it's my configuration that went weird somehow, but I think it should be using `'babel-types'` instead of `'@babel/types'`. Reporting quickly in case it affects everyone updating and not just me.

### LINKED ISSUE #845: 0.4.2 breaks - passes invalid data to babel-helper-evaluate-path
**Describe the bug**

**To Reproduce**

Minimal code to reproduce the bug

```js
export class Component extends Other {
  constructor() {
    super()
    this.flag = true
  }

  main() {
    alert(this.foo)
  }
}
```

**Actual Output**

Nothing!

**Expected Output**

Output when disabling minify preset:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Component = void 0;

class Component extends Other {
  constructor() {
    super();
    this.flag = true;
  }

  main() {
    alert(this.foo);
  }

}

exports.Component = Component;
```

**Stack Trace**

If applicable,

```
TypeError: stmts.entries is not a function
    at compareBindingAndReference (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/babel-helper-evaluate-path/lib/index.js:252:32)
    at evaluateBasedOnControlFlow (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/babel-helper-evaluate-path/lib/index.js:213:27)
    at evaluateIdentifier (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/babel-helper-evaluate-path/lib/index.js:119:26)
    at evaluate (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/babel-helper-evaluate-path/lib/index.js:21:12)
    at PluginPass.Expression (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/babel-plugin-minify-constant-folding/lib/index.js:165:21)
    at PluginPass.newFn (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/@babel/traverse/lib/visitors.js:286:17)
    at newFn (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/swerner/Workspace/sebastian-software/babel-preset-edge/node_modules/@babel/traverse/lib/path/context.js:100:12)
```

**Configuration**

How are you using babel-minify?

Directly from the CLI.

babel-minify version: `0.4.2`
babel version : `7.0.0-beta.46`
babel-minify-config: None

babelrc:

```json5
{
 "presets": [
   [ "@babel/env", { "targets": { "node": '6.9.0', "browsers": [] } } ],
   "minify"
  ]
}
```

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #845
+ fix #844

### CODE REVIEW

File: packages/babel-helper-evaluate-path/src/index.js [hunk 1]
```diff
@@ -181,9 +181,9 @@ function evaluateBasedOnControlFlow(binding, refPath) {
     const declaration = declarator.parentPath;
 
     if (
-      declaration.parentPath.isIfStatement() ||
-      declaration.parentPath.isLoop() ||
-      declaration.parentPath.isSwitchCase()
+      t.isIfStatement(declaration.parentPath) ||
+      t.isLoop(declaration.parentPath) ||
+      t.isSwitchCase(declaration.parentPath)
```
Comment (boopathi) [inline packages/babel-helper-evaluate-path/src/index.js]: this should be `declaration.parentPath.node`.

Comment (boopathi) [reply packages/babel-helper-evaluate-path/src/index.js]: yeah. so isRemoved should be the first check. I think there is a difference between using `t.is` methods on a path and a node.

Comment (vigneshshanmugam) [reply packages/babel-helper-evaluate-path/src/index.js]: I went back to using path.isCheck
